/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as MentorIndexRouteImport } from './routes/mentor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as MentorTaskReviewsRouteImport } from './routes/mentor/task-reviews'
import { Route as MentorStudentsRouteImport } from './routes/mentor/students'
import { Route as MentorProjectsRouteImport } from './routes/mentor/projects'
import { Route as MentorProfileSettingsRouteImport } from './routes/mentor/profile-settings'
import { Route as MentorNotificationsRouteImport } from './routes/mentor/notifications'
import { Route as MentorLiveSessionsRouteImport } from './routes/mentor/live-sessions'
import { Route as MentorCoursesRouteImport } from './routes/mentor/courses'
import { Route as MentorCommunityRouteImport } from './routes/mentor/community'
import { Route as MentorCertificatesRouteImport } from './routes/mentor/certificates'
import { Route as MentorAssessmentsRouteImport } from './routes/mentor/assessments'
import { Route as MentorAnalyticsRouteImport } from './routes/mentor/analytics'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminMentorsRouteImport } from './routes/admin/mentors'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminCertificatesRouteImport } from './routes/admin/certificates'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAdminLayoutRouteImport } from './routes/admin/AdminLayout'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const MentorIndexRoute = MentorIndexRouteImport.update({
  id: '/mentor/',
  path: '/mentor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const MentorTaskReviewsRoute = MentorTaskReviewsRouteImport.update({
  id: '/mentor/task-reviews',
  path: '/mentor/task-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorStudentsRoute = MentorStudentsRouteImport.update({
  id: '/mentor/students',
  path: '/mentor/students',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorProjectsRoute = MentorProjectsRouteImport.update({
  id: '/mentor/projects',
  path: '/mentor/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorProfileSettingsRoute = MentorProfileSettingsRouteImport.update({
  id: '/mentor/profile-settings',
  path: '/mentor/profile-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorNotificationsRoute = MentorNotificationsRouteImport.update({
  id: '/mentor/notifications',
  path: '/mentor/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorLiveSessionsRoute = MentorLiveSessionsRouteImport.update({
  id: '/mentor/live-sessions',
  path: '/mentor/live-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorCoursesRoute = MentorCoursesRouteImport.update({
  id: '/mentor/courses',
  path: '/mentor/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorCommunityRoute = MentorCommunityRouteImport.update({
  id: '/mentor/community',
  path: '/mentor/community',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorCertificatesRoute = MentorCertificatesRouteImport.update({
  id: '/mentor/certificates',
  path: '/mentor/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAssessmentsRoute = MentorAssessmentsRouteImport.update({
  id: '/mentor/assessments',
  path: '/mentor/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAnalyticsRoute = MentorAnalyticsRouteImport.update({
  id: '/mentor/analytics',
  path: '/mentor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/admin/mentors',
  path: '/admin/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/admin/enrollments',
  path: '/admin/enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/admin/certificates',
  path: '/admin/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminLayoutRoute = AdminAdminLayoutRouteImport.update({
  id: '/admin/AdminLayout',
  path: '/admin/AdminLayout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/AdminLayout': typeof AdminAdminLayoutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mentor/analytics': typeof MentorAnalyticsRoute
  '/mentor/assessments': typeof MentorAssessmentsRoute
  '/mentor/certificates': typeof MentorCertificatesRoute
  '/mentor/community': typeof MentorCommunityRoute
  '/mentor/courses': typeof MentorCoursesRoute
  '/mentor/live-sessions': typeof MentorLiveSessionsRoute
  '/mentor/notifications': typeof MentorNotificationsRoute
  '/mentor/profile-settings': typeof MentorProfileSettingsRoute
  '/mentor/projects': typeof MentorProjectsRoute
  '/mentor/students': typeof MentorStudentsRoute
  '/mentor/task-reviews': typeof MentorTaskReviewsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/admin/': typeof AdminIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/AdminLayout': typeof AdminAdminLayoutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mentor/analytics': typeof MentorAnalyticsRoute
  '/mentor/assessments': typeof MentorAssessmentsRoute
  '/mentor/certificates': typeof MentorCertificatesRoute
  '/mentor/community': typeof MentorCommunityRoute
  '/mentor/courses': typeof MentorCoursesRoute
  '/mentor/live-sessions': typeof MentorLiveSessionsRoute
  '/mentor/notifications': typeof MentorNotificationsRoute
  '/mentor/profile-settings': typeof MentorProfileSettingsRoute
  '/mentor/projects': typeof MentorProjectsRoute
  '/mentor/students': typeof MentorStudentsRoute
  '/mentor/task-reviews': typeof MentorTaskReviewsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/admin': typeof AdminIndexRoute
  '/mentor': typeof MentorIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/AdminLayout': typeof AdminAdminLayoutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mentor/analytics': typeof MentorAnalyticsRoute
  '/mentor/assessments': typeof MentorAssessmentsRoute
  '/mentor/certificates': typeof MentorCertificatesRoute
  '/mentor/community': typeof MentorCommunityRoute
  '/mentor/courses': typeof MentorCoursesRoute
  '/mentor/live-sessions': typeof MentorLiveSessionsRoute
  '/mentor/notifications': typeof MentorNotificationsRoute
  '/mentor/profile-settings': typeof MentorProfileSettingsRoute
  '/mentor/projects': typeof MentorProjectsRoute
  '/mentor/students': typeof MentorStudentsRoute
  '/mentor/task-reviews': typeof MentorTaskReviewsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/admin/': typeof AdminIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/student'
    | '/admin/AdminLayout'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/enrollments'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/mentor/analytics'
    | '/mentor/assessments'
    | '/mentor/certificates'
    | '/mentor/community'
    | '/mentor/courses'
    | '/mentor/live-sessions'
    | '/mentor/notifications'
    | '/mentor/profile-settings'
    | '/mentor/projects'
    | '/mentor/students'
    | '/mentor/task-reviews'
    | '/student/courses'
    | '/admin/'
    | '/mentor/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/AdminLayout'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/enrollments'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/mentor/analytics'
    | '/mentor/assessments'
    | '/mentor/certificates'
    | '/mentor/community'
    | '/mentor/courses'
    | '/mentor/live-sessions'
    | '/mentor/notifications'
    | '/mentor/profile-settings'
    | '/mentor/projects'
    | '/mentor/students'
    | '/mentor/task-reviews'
    | '/student/courses'
    | '/admin'
    | '/mentor'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/student'
    | '/admin/AdminLayout'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/enrollments'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/mentor/analytics'
    | '/mentor/assessments'
    | '/mentor/certificates'
    | '/mentor/community'
    | '/mentor/courses'
    | '/mentor/live-sessions'
    | '/mentor/notifications'
    | '/mentor/profile-settings'
    | '/mentor/projects'
    | '/mentor/students'
    | '/mentor/task-reviews'
    | '/student/courses'
    | '/admin/'
    | '/mentor/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
  AdminAdminLayoutRoute: typeof AdminAdminLayoutRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MentorAnalyticsRoute: typeof MentorAnalyticsRoute
  MentorAssessmentsRoute: typeof MentorAssessmentsRoute
  MentorCertificatesRoute: typeof MentorCertificatesRoute
  MentorCommunityRoute: typeof MentorCommunityRoute
  MentorCoursesRoute: typeof MentorCoursesRoute
  MentorLiveSessionsRoute: typeof MentorLiveSessionsRoute
  MentorNotificationsRoute: typeof MentorNotificationsRoute
  MentorProfileSettingsRoute: typeof MentorProfileSettingsRoute
  MentorProjectsRoute: typeof MentorProjectsRoute
  MentorStudentsRoute: typeof MentorStudentsRoute
  MentorTaskReviewsRoute: typeof MentorTaskReviewsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MentorIndexRoute: typeof MentorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/mentor/': {
      id: '/mentor/'
      path: '/mentor'
      fullPath: '/mentor/'
      preLoaderRoute: typeof MentorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/mentor/task-reviews': {
      id: '/mentor/task-reviews'
      path: '/mentor/task-reviews'
      fullPath: '/mentor/task-reviews'
      preLoaderRoute: typeof MentorTaskReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/students': {
      id: '/mentor/students'
      path: '/mentor/students'
      fullPath: '/mentor/students'
      preLoaderRoute: typeof MentorStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/projects': {
      id: '/mentor/projects'
      path: '/mentor/projects'
      fullPath: '/mentor/projects'
      preLoaderRoute: typeof MentorProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/profile-settings': {
      id: '/mentor/profile-settings'
      path: '/mentor/profile-settings'
      fullPath: '/mentor/profile-settings'
      preLoaderRoute: typeof MentorProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/notifications': {
      id: '/mentor/notifications'
      path: '/mentor/notifications'
      fullPath: '/mentor/notifications'
      preLoaderRoute: typeof MentorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/live-sessions': {
      id: '/mentor/live-sessions'
      path: '/mentor/live-sessions'
      fullPath: '/mentor/live-sessions'
      preLoaderRoute: typeof MentorLiveSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/courses': {
      id: '/mentor/courses'
      path: '/mentor/courses'
      fullPath: '/mentor/courses'
      preLoaderRoute: typeof MentorCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/community': {
      id: '/mentor/community'
      path: '/mentor/community'
      fullPath: '/mentor/community'
      preLoaderRoute: typeof MentorCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/certificates': {
      id: '/mentor/certificates'
      path: '/mentor/certificates'
      fullPath: '/mentor/certificates'
      preLoaderRoute: typeof MentorCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/assessments': {
      id: '/mentor/assessments'
      path: '/mentor/assessments'
      fullPath: '/mentor/assessments'
      preLoaderRoute: typeof MentorAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/analytics': {
      id: '/mentor/analytics'
      path: '/mentor/analytics'
      fullPath: '/mentor/analytics'
      preLoaderRoute: typeof MentorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/admin/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/admin/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/AdminLayout': {
      id: '/admin/AdminLayout'
      path: '/admin/AdminLayout'
      fullPath: '/admin/AdminLayout'
      preLoaderRoute: typeof AdminAdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
  AdminAdminLayoutRoute: AdminAdminLayoutRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  MentorAnalyticsRoute: MentorAnalyticsRoute,
  MentorAssessmentsRoute: MentorAssessmentsRoute,
  MentorCertificatesRoute: MentorCertificatesRoute,
  MentorCommunityRoute: MentorCommunityRoute,
  MentorCoursesRoute: MentorCoursesRoute,
  MentorLiveSessionsRoute: MentorLiveSessionsRoute,
  MentorNotificationsRoute: MentorNotificationsRoute,
  MentorProfileSettingsRoute: MentorProfileSettingsRoute,
  MentorProjectsRoute: MentorProjectsRoute,
  MentorStudentsRoute: MentorStudentsRoute,
  MentorTaskReviewsRoute: MentorTaskReviewsRoute,
  AdminIndexRoute: AdminIndexRoute,
  MentorIndexRoute: MentorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
