/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as MentorIndexRouteImport } from './routes/mentor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as MentorTestsRouteImport } from './routes/mentor/tests'
import { Route as MentorStudentsRouteImport } from './routes/mentor/students'
import { Route as MentorReviewsRouteImport } from './routes/mentor/reviews'
import { Route as MentorQueriesRouteImport } from './routes/mentor/queries'
import { Route as MentorClassesRouteImport } from './routes/mentor/classes'
import { Route as MentorMentorLayoutRouteImport } from './routes/mentor/MentorLayout'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminMentorsRouteImport } from './routes/admin/mentors'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAdminLayoutRouteImport } from './routes/admin/AdminLayout'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const MentorIndexRoute = MentorIndexRouteImport.update({
  id: '/mentor/',
  path: '/mentor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const MentorTestsRoute = MentorTestsRouteImport.update({
  id: '/mentor/tests',
  path: '/mentor/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorStudentsRoute = MentorStudentsRouteImport.update({
  id: '/mentor/students',
  path: '/mentor/students',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorReviewsRoute = MentorReviewsRouteImport.update({
  id: '/mentor/reviews',
  path: '/mentor/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorQueriesRoute = MentorQueriesRouteImport.update({
  id: '/mentor/queries',
  path: '/mentor/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorClassesRoute = MentorClassesRouteImport.update({
  id: '/mentor/classes',
  path: '/mentor/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorMentorLayoutRoute = MentorMentorLayoutRouteImport.update({
  id: '/mentor/MentorLayout',
  path: '/mentor/MentorLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/admin/mentors',
  path: '/admin/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminLayoutRoute = AdminAdminLayoutRouteImport.update({
  id: '/admin/AdminLayout',
  path: '/admin/AdminLayout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/AdminLayout': typeof AdminAdminLayoutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mentor/MentorLayout': typeof MentorMentorLayoutRoute
  '/mentor/classes': typeof MentorClassesRoute
  '/mentor/queries': typeof MentorQueriesRoute
  '/mentor/reviews': typeof MentorReviewsRoute
  '/mentor/students': typeof MentorStudentsRoute
  '/mentor/tests': typeof MentorTestsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/admin/': typeof AdminIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/AdminLayout': typeof AdminAdminLayoutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mentor/MentorLayout': typeof MentorMentorLayoutRoute
  '/mentor/classes': typeof MentorClassesRoute
  '/mentor/queries': typeof MentorQueriesRoute
  '/mentor/reviews': typeof MentorReviewsRoute
  '/mentor/students': typeof MentorStudentsRoute
  '/mentor/tests': typeof MentorTestsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/admin': typeof AdminIndexRoute
  '/mentor': typeof MentorIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/AdminLayout': typeof AdminAdminLayoutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mentor/MentorLayout': typeof MentorMentorLayoutRoute
  '/mentor/classes': typeof MentorClassesRoute
  '/mentor/queries': typeof MentorQueriesRoute
  '/mentor/reviews': typeof MentorReviewsRoute
  '/mentor/students': typeof MentorStudentsRoute
  '/mentor/tests': typeof MentorTestsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/admin/': typeof AdminIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/student'
    | '/admin/AdminLayout'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/mentor/MentorLayout'
    | '/mentor/classes'
    | '/mentor/queries'
    | '/mentor/reviews'
    | '/mentor/students'
    | '/mentor/tests'
    | '/student/courses'
    | '/admin/'
    | '/mentor/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/AdminLayout'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/mentor/MentorLayout'
    | '/mentor/classes'
    | '/mentor/queries'
    | '/mentor/reviews'
    | '/mentor/students'
    | '/mentor/tests'
    | '/student/courses'
    | '/admin'
    | '/mentor'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/student'
    | '/admin/AdminLayout'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/mentor/MentorLayout'
    | '/mentor/classes'
    | '/mentor/queries'
    | '/mentor/reviews'
    | '/mentor/students'
    | '/mentor/tests'
    | '/student/courses'
    | '/admin/'
    | '/mentor/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  AdminAdminLayoutRoute: typeof AdminAdminLayoutRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MentorMentorLayoutRoute: typeof MentorMentorLayoutRoute
  MentorClassesRoute: typeof MentorClassesRoute
  MentorQueriesRoute: typeof MentorQueriesRoute
  MentorReviewsRoute: typeof MentorReviewsRoute
  MentorStudentsRoute: typeof MentorStudentsRoute
  MentorTestsRoute: typeof MentorTestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MentorIndexRoute: typeof MentorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/mentor/': {
      id: '/mentor/'
      path: '/mentor'
      fullPath: '/mentor/'
      preLoaderRoute: typeof MentorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/mentor/tests': {
      id: '/mentor/tests'
      path: '/mentor/tests'
      fullPath: '/mentor/tests'
      preLoaderRoute: typeof MentorTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/students': {
      id: '/mentor/students'
      path: '/mentor/students'
      fullPath: '/mentor/students'
      preLoaderRoute: typeof MentorStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/reviews': {
      id: '/mentor/reviews'
      path: '/mentor/reviews'
      fullPath: '/mentor/reviews'
      preLoaderRoute: typeof MentorReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/queries': {
      id: '/mentor/queries'
      path: '/mentor/queries'
      fullPath: '/mentor/queries'
      preLoaderRoute: typeof MentorQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/classes': {
      id: '/mentor/classes'
      path: '/mentor/classes'
      fullPath: '/mentor/classes'
      preLoaderRoute: typeof MentorClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/MentorLayout': {
      id: '/mentor/MentorLayout'
      path: '/mentor/MentorLayout'
      fullPath: '/mentor/MentorLayout'
      preLoaderRoute: typeof MentorMentorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/admin/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/AdminLayout': {
      id: '/admin/AdminLayout'
      path: '/admin/AdminLayout'
      fullPath: '/admin/AdminLayout'
      preLoaderRoute: typeof AdminAdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  AdminAdminLayoutRoute: AdminAdminLayoutRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  MentorMentorLayoutRoute: MentorMentorLayoutRoute,
  MentorClassesRoute: MentorClassesRoute,
  MentorQueriesRoute: MentorQueriesRoute,
  MentorReviewsRoute: MentorReviewsRoute,
  MentorStudentsRoute: MentorStudentsRoute,
  MentorTestsRoute: MentorTestsRoute,
  AdminIndexRoute: AdminIndexRoute,
  MentorIndexRoute: MentorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
