/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskReviewsRouteImport } from './routes/task-reviews'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileSettingsRouteImport } from './routes/profile-settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LiveSessionsRouteImport } from './routes/live-sessions'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TaskReviewsRoute = TaskReviewsRouteImport.update({
  id: '/task-reviews',
  path: '/task-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile-settings',
  path: '/profile-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSessionsRoute = LiveSessionsRouteImport.update({
  id: '/live-sessions',
  path: '/live-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRoute
  '/certificates': typeof CertificatesRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/live-sessions': typeof LiveSessionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/projects': typeof ProjectsRoute
  '/students': typeof StudentsRoute
  '/task-reviews': typeof TaskReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRoute
  '/certificates': typeof CertificatesRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/live-sessions': typeof LiveSessionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/projects': typeof ProjectsRoute
  '/students': typeof StudentsRoute
  '/task-reviews': typeof TaskReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRoute
  '/certificates': typeof CertificatesRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/live-sessions': typeof LiveSessionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/projects': typeof ProjectsRoute
  '/students': typeof StudentsRoute
  '/task-reviews': typeof TaskReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assessments'
    | '/certificates'
    | '/community'
    | '/courses'
    | '/live-sessions'
    | '/notifications'
    | '/profile-settings'
    | '/projects'
    | '/students'
    | '/task-reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assessments'
    | '/certificates'
    | '/community'
    | '/courses'
    | '/live-sessions'
    | '/notifications'
    | '/profile-settings'
    | '/projects'
    | '/students'
    | '/task-reviews'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assessments'
    | '/certificates'
    | '/community'
    | '/courses'
    | '/live-sessions'
    | '/notifications'
    | '/profile-settings'
    | '/projects'
    | '/students'
    | '/task-reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssessmentsRoute: typeof AssessmentsRoute
  CertificatesRoute: typeof CertificatesRoute
  CommunityRoute: typeof CommunityRoute
  CoursesRoute: typeof CoursesRoute
  LiveSessionsRoute: typeof LiveSessionsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProjectsRoute: typeof ProjectsRoute
  StudentsRoute: typeof StudentsRoute
  TaskReviewsRoute: typeof TaskReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/task-reviews': {
      id: '/task-reviews'
      path: '/task-reviews'
      fullPath: '/task-reviews'
      preLoaderRoute: typeof TaskReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-settings': {
      id: '/profile-settings'
      path: '/profile-settings'
      fullPath: '/profile-settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-sessions': {
      id: '/live-sessions'
      path: '/live-sessions'
      fullPath: '/live-sessions'
      preLoaderRoute: typeof LiveSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssessmentsRoute: AssessmentsRoute,
  CertificatesRoute: CertificatesRoute,
  CommunityRoute: CommunityRoute,
  CoursesRoute: CoursesRoute,
  LiveSessionsRoute: LiveSessionsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProjectsRoute: ProjectsRoute,
  StudentsRoute: StudentsRoute,
  TaskReviewsRoute: TaskReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
